"""cria tabelas iniciais do BrewTrack

Revision ID: 2a1dd9751bd9
Revises:
Create Date: 2026-07-28 20:46:27.153366

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a1dd9751bd9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "barris",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column("capacidade_litros", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DISPONIVEL",
                "COM_CLIENTE",
                "EM_MANUTENCAO",
                "EXTRAVIADO",
                "BAIXADO",
                name="status_barril_enum",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="DISPONIVEL",
            nullable=False,
        ),
        sa.Column("data_aquisicao", sa.Date(), nullable=True),
        sa.Column("observacao", sa.Text(), nullable=True),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "capacidade_litros > 0", name=op.f("ck_barris_capacidade_litros_positiva")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_barris")),
        sa.UniqueConstraint("codigo", name=op.f("uq_barris_codigo")),
    )
    op.create_index(op.f("ix_barris_status"), "barris", ["status"], unique=False)
    op.create_table(
        "clientes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "tipo_pessoa",
            sa.Enum(
                "FISICA",
                "JURIDICA",
                name="tipo_pessoa_enum",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("nome_razao_social", sa.String(length=160), nullable=False),
        sa.Column("nome_fantasia", sa.String(length=160), nullable=True),
        sa.Column("documento", sa.String(length=18), nullable=True),
        sa.Column("telefone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=180), nullable=True),
        sa.Column("logradouro", sa.String(length=180), nullable=True),
        sa.Column("numero", sa.String(length=20), nullable=True),
        sa.Column("complemento", sa.String(length=100), nullable=True),
        sa.Column("bairro", sa.String(length=100), nullable=True),
        sa.Column("cidade", sa.String(length=100), nullable=True),
        sa.Column("estado", sa.String(length=2), nullable=True),
        sa.Column("cep", sa.String(length=9), nullable=True),
        sa.Column(
            "ativo", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clientes")),
        sa.UniqueConstraint("documento", name=op.f("uq_clientes_documento")),
    )
    op.create_index(
        op.f("ix_clientes_nome_razao_social"),
        "clientes",
        ["nome_razao_social"],
        unique=False,
    )
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=180), nullable=False),
        sa.Column("senha_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "perfil",
            sa.Enum(
                "ADMINISTRADOR",
                "OPERADOR",
                "CONSULTA",
                name="perfil_usuario_enum",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="OPERADOR",
            nullable=False,
        ),
        sa.Column(
            "ativo", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usuarios")),
        sa.UniqueConstraint("email", name=op.f("uq_usuarios_email")),
    )
    op.create_table(
        "movimentacoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("barril_id", sa.Integer(), nullable=False),
        sa.Column("cliente_id", sa.Integer(), nullable=True),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "ENTRADA_ESTOQUE",
                "SAIDA_CLIENTE",
                "RETORNO_CLIENTE",
                "ENVIO_MANUTENCAO",
                "RETORNO_MANUTENCAO",
                "BAIXA",
                "AJUSTE",
                name="tipo_movimentacao_enum",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "data_movimentacao",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("data_prevista_retorno", sa.Date(), nullable=True),
        sa.Column("responsavel_recebimento", sa.String(length=120), nullable=True),
        sa.Column("observacao", sa.Text(), nullable=True),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "tipo NOT IN ('SAIDA_CLIENTE', 'RETORNO_CLIENTE') OR cliente_id IS NOT NULL",
            name=op.f("ck_movimentacoes_cliente_obrigatorio_saida_retorno"),
        ),
        sa.ForeignKeyConstraint(
            ["barril_id"],
            ["barris.id"],
            name=op.f("fk_movimentacoes_barril_id_barris"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clientes.id"],
            name=op.f("fk_movimentacoes_cliente_id_clientes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name=op.f("fk_movimentacoes_usuario_id_usuarios"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_movimentacoes")),
    )
    op.create_index(
        op.f("ix_movimentacoes_barril_id"), "movimentacoes", ["barril_id"], unique=False
    )
    op.create_index(
        op.f("ix_movimentacoes_cliente_id"),
        "movimentacoes",
        ["cliente_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_movimentacoes_data_movimentacao"),
        "movimentacoes",
        ["data_movimentacao"],
        unique=False,
    )
    op.create_index(
        op.f("ix_movimentacoes_tipo"), "movimentacoes", ["tipo"], unique=False
    )
    op.create_index(
        op.f("ix_movimentacoes_usuario_id"),
        "movimentacoes",
        ["usuario_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_movimentacoes_usuario_id"), table_name="movimentacoes")
    op.drop_index(op.f("ix_movimentacoes_tipo"), table_name="movimentacoes")
    op.drop_index(
        op.f("ix_movimentacoes_data_movimentacao"), table_name="movimentacoes"
    )
    op.drop_index(op.f("ix_movimentacoes_cliente_id"), table_name="movimentacoes")
    op.drop_index(op.f("ix_movimentacoes_barril_id"), table_name="movimentacoes")
    op.drop_table("movimentacoes")
    op.drop_table("usuarios")
    op.drop_index(op.f("ix_clientes_nome_razao_social"), table_name="clientes")
    op.drop_table("clientes")
    op.drop_index(op.f("ix_barris_status"), table_name="barris")
    op.drop_table("barris")
    # ### end Alembic commands ###
